source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cheneylew/cocoapods-specs.git'

use_frameworks!

def shared_private_pods
    pod 'DJMacros', '~> 0.7.4'
    pod 'KKCategories', '~> 0.3.2'
end

target 'VisionUIKit_Example' do
    #pod 'VisionUIKit', :path => '../'
    shared_private_pods
    
  target 'VisionUIKit_Tests' do
    inherit! :search_paths
    
  end
end
