source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cheneylew/cocoapods-specs.git'
source 'https://github.com/cheneylew/hyh-specs.git'

use_frameworks!

def shared_private_pods
    pod 'DJMacros', '~> 0.7.12'
    pod 'KKCategories', '~> 0.3.8'
    pod 'DJDebug', '~> 0.1.1'
#    pod 'NavyUIKit', '~> 0.1.53'
end

def good_lib_pods
    pod 'JHChainableAnimations', '~> 1.3.0'
    pod 'ReactiveCocoa', '~> 2.5'
    #    pod 'NSLogger', '~> 1.7.0'
    #    pod 'CocoaLumberjack'
    pod 'DCCLogSystem', '~> 0.1.2'
    pod 'CRToast'                   #类似QQ音乐导航栏上方弹出的提示
    pod 'Toast', '~> 3.1.0'
    
    #VC 设置单独的导航条,不是之前那样使用一个全局统一的导航条。
    #无法使用 self.navigationItem.rightBarButtonItem 等来设置导航按钮，而必须自己手动往 navigationBar 上加；
    #无法使用 self.title 来修改导航标题，而必须自己添加监听；
    #无法方便地设置 navigationBarHidden；
    #无法方便地自动调整 contentInsets。
    pod 'RTRootNavigationController'    #存在bug。
    pod 'JTNavigationController'        #网易云音乐,不建议使用在正式项目中，效果不如RTRootNavigationController
#    pod 'WXSTransition'                 #各种转场动画 https://github.com/alanwangmodify/WXSTransition
    pod 'XMAdScrollView', '~> 1.3'      #iOS无限轮播器，支持重用，旋转
#    pod 'XMChatBar', '~> 1.3.0'         #模仿微信聊天输入框
#    pod 'XMNetworking'                  #对AFNetworking进行封装后的请求库
    pod 'DJNetworking'
    pod 'MBProgressHUD'
    pod 'DZNEmptyDataSet'                #处理空表和集合视图
    pod 'PDTSimpleCalendar'              #日历组件
    pod 'MagicalRecord'                 #CoreData二次封装
#    pod 'Chameleon'                     #颜色框架。它扩展了 UIColor，加入了漂亮的、现代扁平化风格的颜色。它也让我们可以从由我们自己定义的颜色创建出调色板
#    pod 'PKRevealController'            #侧滑的菜单(左，右，或者同时)，滑向哪边是看你的使用习惯
    pod 'SlackTextViewController'
    pod 'FontAwesomeKit'                #简单地添加字体到你的项目当中，另外还有很多其它方面的功能。
    pod 'MGSwipeTableCell'              #滑动Cell，更多删除
#    pod 'Concorde'                      #让图片渐进的加载出来
    pod 'AvoidCrash'                    #避免常见崩溃
    pod 'MJExtension'                   #用于JSON与对象之间模型转换
    pod 'DLPhotoPicker'                 #类似微信照片选取
    pod 'ZLPhotoBrowser'                #照片预览
#    pod 'PYPhotoBrowser'                #
#    pod 'PPHTMLImagePreviewDemo'        #Html中的图片，点击后原生图片预览
    pod 'JYCarousel'                    #图片轮播
#    pod 'Popover', '~> 1.0.1'           #微型菜单弹窗(类似QQ和微信右上角弹窗) https://github.com/lifution/Popover
#    pod 'XMNPhoto', '~> 1.1.0'          #浏览展示一组图片或从相册选取图片
    pod 'KVOController'                 #facebook MVVM KVO
    pod 'MGJRouter', '~> 0.9.3'         #蘑菇街路由
    pod 'Task', '~> 1.1'                #任务流
end

target 'VisionUIKit_Example' do
    good_lib_pods
    shared_private_pods
    
  target 'VisionUIKit_Tests' do
    inherit! :search_paths
    
  end
end
